distributium_frontend_product:
    resource: "@DistributiumFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

distributium_backend:
    resource: "@DistributiumBackendBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
#
# Support for LiipImagineBundle
#_imagine:
#    resource: .
#    type:     imagine

_front:
    resource: routing_front.yml

_admin:
    resource: routing_admin.yml
    prefix:   /admin

_api:
    resource: routing_api.yml
    prefix:   /api

_distributium_api:
    resource: routing_distributium_api.yml
    prefix:   /distributium_api

fos_js_routing:
            resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

