services:
    distributium_backend.admin.item:
        class: Distributium\BackendBundle\Admin\ItemAdmin
        arguments: [~, Distributium\BackendBundle\Entity\Item, DistributiumBackendBundle:ItemAdmin]
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Product}

    distributium_backend.admin.category:
        class: Distributium\BackendBundle\Admin\CategoryAdmin
        arguments: [~, Distributium\BackendBundle\Entity\Category, DistributiumBackendBundle:CategoryAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Category}

    distributium_backend.admin.image:
        class: Distributium\BackendBundle\Admin\ImageAdmin
        arguments: [~, Distributium\BackendBundle\Entity\Image, DistributiumBackendBundle:ImageAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Image}

    distributium_backend.admin.company:
        class: Distributium\BackendBundle\Admin\CompanyAdmin
        arguments: [~, Distributium\BackendBundle\Entity\Company, DistributiumBackendBundle:CompanyAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Company}

    distributium_backend.admin.lodging_type:
        class: Distributium\BackendBundle\Admin\LodgingTypeAdmin
        arguments: [~, Distributium\BackendBundle\Entity\LodgingType, DistributiumBackendBundle:LodgingTypeAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: LodgingType}
