services:
    distributium.frontend.block.productlist:
        class: Distributium\FrontendBundle\Block\ProductlistBlockService
        arguments: [ "distributium.frontend.block.productlist", @templating ]
        tags:
            - { name: sonata.block }
    distributium.product.controller.api.list:
        class: Distributium\FrontendBundle\Controller\Api\ProductController
        type: rest
